-- common deps first
require('common')
require('theme')
require('mini_plugs')
require('files')
require('treesitter')
require('lsp')
require('typescript')
require('test_runner')
-- require('rusties')
-- require('clojure')
require('ai')
require('ui')
require('git')
