require "config.functions"
require "config.files"
require "config.theme"
require "config.editing"
require "config.ui"
require "config.motion"
require "config.services"

require "config.options"
require "config.keymaps"
require "config.lazy"
