-- spec "config.theme.tokyonight"
-- spec "config.theme.kanagawa"
-- spec "config.theme.rose_pine"
-- spec "config.theme.pyramid"
-- spec "config.theme.catppuccin"
-- spec "config.theme.solarized"
spec "config.theme.zenbones"
-- spec "config.theme.everforest"
-- spec "config.theme.mini"
