spec "config.files.oil"
-- spec "config.files.neotree"
-- spec "config.files.fzf"
-- spec "config.files.jfind"
spec "config.files.telescope"
spec "config.files.harpoon"
spec "config.files.neogit"
-- spec "config.files.mini"
-- spec "config.files.ranger"
