spec "config.editing.spectre"
spec "config.editing.mini_comment"
spec "config.editing.mini_pairs"
spec "config.editing.surround"
-- spec "config.editing.refactoring"
spec "config.editing.rename"
spec "config.editing.ts_autotag"
