spec "config.visual.mini_indent"
spec "config.visual.mini_statusline"
spec "config.visual.dropbar"
spec "config.visual.treesitter"
spec "config.visual.gitsigns"
spec "config.visual.todo"
spec "config.visual.dressing"
